-- ---------------------------------------------------------------------------------
--  Database.
--
--  Author:
--    Tsanda Andrej
--
--  Version for HSQLDB.
--
-- ---------------------------------------------------------------------------------

CREATE SCHEMA smart_incubator;


-- ---------------------------------------------------------------------------------
-- Table for storing modes.
-- ---------------------------------------------------------------------------------
CREATE TABLE modes
(
  id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
  mode_name VARCHAR_IGNORECASE(255) NOT NULL,
  activation_status BOOLEAN NOT NULL,
  up_lim_temperature DECIMAL(5,2) NOT NULL,
  low_lim_temperature DECIMAL(5,2) NOT NULL,
  up_lim_humidity DECIMAL(5,2) NOT NULL,
  low_lim_humidity DECIMAL(5,2) NOT NULL,
  engine_speed INT NOT NULL,
  work_time INT NOT NULL,
  create_time TIMESTAMP NULL
);


-- ---------------------------------------------------------------------------------
-- Table for storing readings from sensors (eg, temperature, humidity, etc.).
-- ---------------------------------------------------------------------------------
CREATE TABLE statistics
(
  id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
  temperature_sensor_1 DECIMAL(5,2) NOT NULL,
  temperature_sensor_2 DECIMAL(5,2) NOT NULL,
  temperature_sensor_3 DECIMAL(5,2) NOT NULL,
  humidity_sensor_1 DECIMAL(5,2) NOT NULL,
  create_time TIMESTAMP NULL
);